<?php if(!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
<p><a class="register-box" title="Register to Get Free Coupon1" href="javascript:signin();" target="_self"> <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'wysiwyg/infortis/ultimo/slideshow/register_now_02.jpg'?>" alt="" /></a></p>
<style>.register-box img {
    margin-bottom: 25px !important;
}</style>
<?php endif; ?>